"""DataBase change postID

Revision ID: 5fa5c53d497a
Revises: f7eb09c2619a
Create Date: 2025-01-08 13:53:47.546919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa5c53d497a'
down_revision: Union[str, None] = 'f7eb09c2619a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('postID', sa.UUID(), nullable=True))
    op.drop_column('collections', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'postID')
    # ### end Alembic commands ###
