"""DataBase change v3

Revision ID: f7eb09c2619a
Revises: fd1dce61feb2
Create Date: 2025-01-08 13:19:16.983873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7eb09c2619a'
down_revision: Union[str, None] = 'fd1dce61feb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_names',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.add_column('collections', sa.Column('userID', sa.UUID(), nullable=True))
    op.drop_column('collections', 'user_id')
    op.add_column('hw_cars', sa.Column('userID', sa.UUID(), nullable=True))
    op.add_column('hw_cars', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('hw_cars', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hw_cars', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('hw_cars', 'username')
    op.drop_column('hw_cars', 'userID')
    op.add_column('collections', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'userID')
    op.drop_table('collection_names', schema='public')
    # ### end Alembic commands ###
